name: node-bench

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  bench:
    uses: jr200-labs/github-action-templates/.github/workflows/node-bench.yaml@master
    with:
      runner: ${{ fromJSON(vars.RUNNER_PROFILES)[vars.RUNNER_PROFILE].default }}
      warn-threshold: ${{ vars.BENCH_WARN_THRESHOLD || '10' }}
      fail-threshold: ${{ vars.BENCH_FAIL_THRESHOLD || '50' }}
