#!/usr/bin/env bash
# Validate the shared Renovate uv.lock regeneration rule.
#
# Renovate applies postUpgradeTasks from the matched dependency config. In
# grouped Python PRs, scoping this rule with matchFileNames has failed to attach
# the task to pyproject.toml updates, leaving uv.lock stale while CI rejects the
# branch with `uv lock --check`.

set -euo pipefail

file="${1:-default.json}"
workflow="${2:-.github/workflows/renovate.yaml}"

if [[ ! -f "$file" ]]; then
  echo "ERROR: config file not found: $file" >&2
  exit 2
fi

if [[ ! -f "$workflow" ]]; then
  echo "ERROR: workflow file not found: $workflow" >&2
  exit 2
fi

if ! jq -e . "$file" >/dev/null 2>&1; then
  echo "ERROR: $file is not valid JSON" >&2
  exit 2
fi

rule_count=$(jq '
  [
    .packageRules[]?
    | select((.postUpgradeTasks.commands // []) == ["uv lock"])
    | select((.postUpgradeTasks.installTools // {}) == {"python": {}, "uv": {}})
    | select((.postUpgradeTasks.fileFilters // []) == ["uv.lock"])
    | select((.matchManagers // []) | index("pep621"))
    | select((.matchManagers // []) | index("custom.regex"))
  ]
  | length
' "$file")

if [[ "$rule_count" != "1" ]]; then
  echo "FAIL: expected exactly one uv.lock postUpgradeTasks rule for pep621/custom.regex managers with installTools.python and installTools.uv; found ${rule_count}" >&2
  exit 1
fi

file_scoped_count=$(jq '
  [
    .packageRules[]?
    | select((.postUpgradeTasks.commands // []) == ["uv lock"])
    | select(has("matchFileNames"))
  ]
  | length
' "$file")

if [[ "$file_scoped_count" != "0" ]]; then
  echo "FAIL: uv.lock postUpgradeTasks rule must not use matchFileNames; it can prevent Renovate from running the task on grouped pyproject.toml updates" >&2
  exit 1
fi

shared_ref_uv_lock_count=$(jq '
  [
    .packageRules[]?
    | select((.postUpgradeTasks.commands // []) == ["uv lock"])
    | select(((.matchPackageNames // []) | index("!jr200-labs/github-action-templates")) | not)
  ]
  | length
' "$file")

if [[ "$shared_ref_uv_lock_count" != "0" ]]; then
  echo "FAIL: uv.lock postUpgradeTasks rule must exclude the shared workflow ref package with negative matchPackageNames; shared-ref repos are not necessarily Python projects" >&2
  exit 1
fi

internal_minimum_age_rule_count=$(jq '
  [
    .packageRules[]?
    | select(.minimumReleaseAge == null)
    | select((.matchPackageNames // []) | index("polars-hist-db"))
    | select((.matchPackageNames // []) | index("whengas/**"))
    | select((.matchPackageNames // []) | index("jr200-labs/**"))
    | select((.matchPackageNames // []) | index("janeway-labs/**"))
  ]
  | length
' "$file")

if [[ "$internal_minimum_age_rule_count" != "1" ]]; then
  echo "FAIL: internal packages must opt out of Renovate minimumReleaseAge so internal rollouts are immediate" >&2
  exit 1
fi

private_git_rule_count=$(jq '
  [
    .packageRules[]?
    | select((.matchManagers // []) | index("custom.regex"))
    | select((.matchPackageNames // []) | index("whengas/**"))
    | select((.matchPackageNames // []) | index("jr200-labs/**"))
    | select((.matchPackageNames // []) | index("janeway-labs/**"))
    | select(.groupName == "private git Python dependencies")
    | select(.groupSlug == "private-git-python")
    | select(.skipArtifactsUpdate == true)
  ]
  | length
' "$file")

if [[ "$private_git_rule_count" != "1" ]]; then
  echo "FAIL: private git Python deps must be split from PyPI groups and skip Renovate artifact updates; uv.lock is regenerated by postUpgradeTasks" >&2
  exit 1
fi

uv_setup_line="$(grep -n 'uses: astral-sh/setup-uv@' "$workflow" | head -n1 | cut -d: -f1 || true)"
uv_repair_line="$(grep -n 'repair-renovate-uv-lock-branches.sh' "$workflow" | head -n1 | cut -d: -f1 || true)"
if [[ -z "$uv_setup_line" || -z "$uv_repair_line" || "$uv_setup_line" -ge "$uv_repair_line" ]]; then
  echo "FAIL: Renovate workflow must install uv before repairing Renovate Python branches" >&2
  exit 1
fi

if ! sed -n "$((uv_setup_line - 2)),$((uv_setup_line + 2))p" "$workflow" \
  | grep -q "inputs.dry-run == '' && hashFiles('pyproject.toml') != ''"; then
  echo "FAIL: Renovate workflow must only run setup-uv for the post-Renovate Python repair path" >&2
  exit 1
fi

echo "lint-renovate-uv-lock-task: ok" >&2
