#!/usr/bin/env bash
# Validate the shared Renovate uv.lock regeneration rule.
#
# Renovate applies postUpgradeTasks from the matched dependency config. In
# grouped Python PRs, scoping this rule with matchFileNames has failed to attach
# the task to pyproject.toml updates, leaving uv.lock stale while CI rejects the
# branch with `uv lock --check`.

set -euo pipefail

file="${1:-default.json}"
workflow="${2:-.github/workflows/renovate.yaml}"

if [[ ! -f "$file" ]]; then
  echo "ERROR: config file not found: $file" >&2
  exit 2
fi

if [[ ! -f "$workflow" ]]; then
  echo "ERROR: workflow file not found: $workflow" >&2
  exit 2
fi

if ! jq -e . "$file" >/dev/null 2>&1; then
  echo "ERROR: $file is not valid JSON" >&2
  exit 2
fi

rule_count=$(jq '
  [
    .packageRules[]?
    | select((.postUpgradeTasks.commands // []) == ["uv lock --refresh"])
    | select((.postUpgradeTasks.installTools // {}) == {"python": {}, "uv": {}})
    | select((.postUpgradeTasks.fileFilters // []) == ["uv.lock"])
    | select((.matchManagers // []) | index("pep621"))
    | select((.matchManagers // []) | index("custom.regex"))
  ]
  | length
' "$file")

if [[ "$rule_count" != "1" ]]; then
  echo "FAIL: expected exactly one uv.lock postUpgradeTasks rule for pep621/custom.regex managers with installTools.python and installTools.uv; found ${rule_count}" >&2
  exit 1
fi

file_scoped_count=$(jq '
  [
    .packageRules[]?
    | select((.postUpgradeTasks.commands // []) == ["uv lock --refresh"])
    | select(has("matchFileNames"))
  ]
  | length
' "$file")

if [[ "$file_scoped_count" != "0" ]]; then
  echo "FAIL: uv.lock postUpgradeTasks rule must not use matchFileNames; it can prevent Renovate from running the task on grouped pyproject.toml updates" >&2
  exit 1
fi

shared_ref_uv_lock_count=$(jq '
  [
    .packageRules[]?
    | select((.postUpgradeTasks.commands // []) == ["uv lock --refresh"])
    | select(((.matchPackageNames // []) | index("!jr200-labs/github-action-templates")) | not)
  ]
  | length
' "$file")

if [[ "$shared_ref_uv_lock_count" != "0" ]]; then
  echo "FAIL: uv.lock postUpgradeTasks rule must exclude the shared workflow ref package with negative matchPackageNames; shared-ref repos are not necessarily Python projects" >&2
  exit 1
fi

allowed_refresh_count=$(grep -F -c 'RENOVATE_ALLOWED_COMMANDS: '\''^(?:uv lock(?: --refresh)?|' "$workflow" || true)
if [[ "$allowed_refresh_count" != "2" ]]; then
  echo "FAIL: both Renovate passes must allow uv lock --refresh" >&2
  exit 1
fi

internal_minimum_age_rule_count=$(jq '
  [
    .packageRules[]?
    | select(.minimumReleaseAge == null)
    | select((.matchPackageNames // []) | index("polars-hist-db"))
    | select((.matchPackageNames // []) | index("whengas/**"))
    | select((.matchPackageNames // []) | index("jr200-labs/**"))
    | select((.matchPackageNames // []) | index("janeway-labs/**"))
  ]
  | length
' "$file")

if [[ "$internal_minimum_age_rule_count" != "1" ]]; then
  echo "FAIL: internal packages must opt out of Renovate minimumReleaseAge so internal rollouts are immediate" >&2
  exit 1
fi

private_git_rule_count=$(jq '
  [
    .packageRules[]?
    | select((.matchManagers // []) | index("custom.regex"))
    | select((.matchPackageNames // []) | index("whengas/**"))
    | select((.matchPackageNames // []) | index("jr200-labs/**"))
    | select((.matchPackageNames // []) | index("janeway-labs/**"))
    | select(.groupName == "private git Python dependencies")
    | select(.groupSlug == "private-git-python")
    | select(.skipArtifactsUpdate == true)
  ]
  | length
' "$file")

if [[ "$private_git_rule_count" != "1" ]]; then
  echo "FAIL: private git Python deps must be split from PyPI groups and skip Renovate artifact updates; uv.lock is regenerated by postUpgradeTasks" >&2
  exit 1
fi

branch_digest_manager_count=$(jq '
  [
    .customManagers[]?
    | select(.customType == "regex")
    | select(.datasourceTemplate == "git-refs")
    | select((.managerFilePatterns // []) == ["/(^|/)uv\\.lock$/"])
    | select((.matchStrings // []) | length == 1)
    | select(.matchStrings[0] | contains("(?<currentValue>master|main)"))
    | select(.matchStrings[0] | contains("(?<currentDigest>[0-9a-f]{40})"))
    | select(.matchStrings[0] | contains("(?<packageName>https://github"))
  ]
  | length
' "$file")

if [[ "$branch_digest_manager_count" != "1" ]]; then
  echo "FAIL: expected exactly one git-refs custom manager for master/main digests in uv.lock" >&2
  exit 1
fi

branch_digest_pattern=$(jq -r '
  .customManagers[]
  | select(.datasourceTemplate == "git-refs")
  | .matchStrings[0]
' "$file")

BRANCH_DIGEST_PATTERN="$branch_digest_pattern" node <<'NODE'
const pattern = new RegExp(process.env.BRANCH_DIGEST_PATTERN);
const digest = "0123456789abcdef0123456789abcdef01234567";
const branch = `name = "demo-package"\nversion = "1.2.3"\nsource = { git = "https://github.com/example/demo-package.git?rev=master#${digest}" }`;
const match = pattern.exec(branch);
if (!match || match.groups.depName !== "demo-package" || match.groups.currentValue !== "master" || match.groups.currentDigest !== digest) {
  throw new Error("git branch uv.lock fixture was not extracted correctly");
}
if (pattern.test(branch.replace("rev=master", "rev=v1.2.3"))) {
  throw new Error("git tag uv.lock fixture must not match the branch digest manager");
}
NODE

uv_setup_line="$(grep -n 'uses: astral-sh/setup-uv@' "$workflow" | head -n1 | cut -d: -f1 || true)"
uv_repair_line="$(grep -n 'repair-renovate-uv-lock-branches.sh' "$workflow" | head -n1 | cut -d: -f1 || true)"
if [[ -z "$uv_setup_line" || -z "$uv_repair_line" || "$uv_setup_line" -ge "$uv_repair_line" ]]; then
  echo "FAIL: Renovate workflow must install uv before repairing Renovate Python branches" >&2
  exit 1
fi

if ! sed -n "$((uv_setup_line - 2)),$((uv_setup_line + 2))p" "$workflow" \
  | grep -q "inputs.dry-run == '' && inputs.repair-branches && hashFiles('pyproject.toml') != ''"; then
  echo "FAIL: Renovate workflow must only run setup-uv for the post-Renovate Python repair path" >&2
  exit 1
fi

echo "lint-renovate-uv-lock-task: ok" >&2
