name: template-build-sphinx-docs

on:
  workflow_call:
    inputs:
      checkout-ref:
        description: "checkout ref"
        required: false
        type: string
        default: "refs/heads/master"
      unused-variable:
        description: unused-variable
        required: false
        type: string
        default: dummy    
  
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.checkout-ref }}

      # - name: Read Python version from .python-version and add as environment variable
      #   run: |
      #     PYTHON_VERSION=$(cut -d. -f1,2 < .python-version)
      #     echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_ENV
      #     echo "PYTHON_VERSION=$PYTHON_VERSION"

      # - name: Setup Python version ${{ env.PYTHON_VERSION }}
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.2
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --with dev

      - name: Build HTML
        uses: ammaraskar/sphinx-action@8.2.3
        with:
          pre-build-command: >-
            apt-get update && apt-get install -y pandoc
          docs-folder: "docs/"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/build/html/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          publish_branch: gh-pages
          enable_jekyll: false
          force_orphan: true

