name: template-preconfigure

on:
  workflow_call:
    inputs:
      event_name:
        description: toJson(github.event_name)
        required: true
        type: string
      event:
        description: toJson(github.event)
        required: true
        type: string
    outputs:
      context:
        value: ${{ jobs.configure.outputs.context }}

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      context: ${{ steps.set-context.outputs.context }}
    steps:
      - id: set-context
        run: |
          if [ "${{ inputs.event_name }}" == "workflow_dispatch" ]; then
            JSON_DATA=$(echo '${{ toJson(fromJson(inputs.event).inputs) }}' | jq -c)
          else
            JSON_DATA=$(echo '${{ toJson(fromJson(inputs.event).client_payload) }}' | jq -c)
          fi

          echo "context=$JSON_DATA" >> $GITHUB_OUTPUT
