name: template-publish-pypi

on:
  workflow_call:
    inputs:
      build-args:
        description: "build-args"
        required: false
        type: string
        default: -v
      publish-args:
        description: "publish-args"
        required: false
        type: string
        default: -vvv
    secrets:
      pypi_api_token:
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.2
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Build wheel
        run: poetry build ${{ inputs.build-args }}

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.pypi_api_token }}
        run: poetry publish ${{ inputs.publish-args }} 
